#!/bin/bash
#
# Run all the libaddr tests with coverage

set -e

if test "$1" = "--help" -o "$1" = "-h"
then
    echo "Usage: $0 [--opt]"
    echo "where --opt is one of:"
    echo "   --help | -h    disply this help screen"
    exit 1;
fi

TEST_NAME=
if test -n "$1"
then
    TEST_NAME="$1"
fi


start_date=`date`
SOURCE=`pwd`
VERSION=`dpkg-parsechangelog --show-field Version | sed -e 's/~.*//' -e 's/\(^[0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/'`
echo "***"
echo "*** libaddr coverage for version $VERSION ($start_date)"
echo "***"
mkdir -p tmp/coverage
rm -rf tmp/coverage/*
cd tmp/coverage
mkdir BUILD
cd BUILD
# request coverage in this build
dist=`cd ../../../../../../; pwd`/BUILD/dist
modules=$dist/share/cmake-3.5/Modules
cmake -DCMAKE_INSTALL_PREFIX:PATH=$dist \
    -DCMAKE_MODULE_PATH:PATH=$modules \
    -DCMAKE_BUILD_TYPE=Debug \
    -Daddr_library_COVERAGE:BOOL=ON \
    ../../..
cd ..
echo
echo "***"
echo "*** compile (`date`)"
echo "***"
VERBOSE=1 make -j 8 -C BUILD
echo
echo "***"
echo "*** run (`date`)"
echo "***"
if test `BUILD/tests/addr_test --version` != "$VERSION"
then
    echo "the version of addr_test (`BUILD/tests/addr_test --version`) is not equal to the project version ($VERSION)"
    exit 1;
fi

# We test the pipe status on exit to detect whether the test failed
echo "Start running the tests on `date`" >test_log.txt
echo >>test_log.txt
BUILD/tests/addr_test $TEST_NAME 2>&1 | tee -a test_log.txt; test ${PIPESTATUS[0]} -eq 0
echo >>test_log.txt
echo "Finished running the tests on `date`" >>test_log.txt
echo
echo "***"
echo "*** gcov/lcov (`date`)"
echo "***"

# Choose one of the following gcov commands
mkdir -p gcov
cd gcov
gcov -o ../BUILD/src/CMakeFiles/libaddr.dir/addr.cpp.gcno ../../../src/addr.cpp
cd ..


#lcov --capture --directory BUILD --output-file coverage.info
# The following lcov options can be used under Ubuntu 14.04+
# Use --no-external and --base-directory $SOURCE
# to avoid /usr/include and other unwanted files
# (only available in lcov version 1.10+)
lcov --capture --no-external --directory BUILD --base-directory $SOURCE --output-file coverage.info
mkdir -p html
genhtml --legend --demangle-cpp --no-branch-coverage --show-details coverage.info --output-directory html


end_date=`date`

# Statistics
echo "<html><head><title>libaddr $VERSION statistics</title></head><body>" >html/statistics.html
echo "<h3>Statistics of the libaddr $VERSION code</h3><pre>" >>html/statistics.html
cloc $SOURCE/src/ >>html/statistics.html
echo "</pre><h3>Statistics of the libaddr $VERSION tests</h3><pre>" >>html/statistics.html
cloc $SOURCE/tests/ >>html/statistics.html
#echo "</pre><h3>Statistics of libaddr scripts $VERSION</h3><pre>" >>html/statistics.html
#cloc $SOURCE/scripts/ >>html/statistics.html
echo "</pre></body></html>" >>html/statistics.html

# Test output (Logs)
echo "<html><head><title>libaddr $VERSION test logs</title></head><body><h3>Logs for the libaddr $VERSION tests</h3><p>Tests started on $start_date and finished on $end_date</p><pre>" >html/test_log.html
if test -f test_log.txt
then
    # If test_log.txt does not exist, the user got the logs in the
    # console already
    cat test_log.txt >>html/test_log.html
fi
echo "</pre></body></html>" >>html/test_log.html


#if test -f test_log.txt
#then
#    echo "***"
#    echo "*** publication to libaddr.snapwebsites.org ($end_date)"
#    echo "***"
#
#    # For publication, if that directory does not exist, you probably don't
#    # have a website to display this data
#    if test -d /usr/clients/www/libaddr.snapwebsites.org/public_html
#    then
#            cp $SOURCE/dev/index.php /usr/clients/www/libaddr.snapwebsites.org/public_html/.
#            mkdir -p /usr/clients/www/libaddr.snapwebsites.org/public_html/libaddr-$VERSION
#            cp -r html/* /usr/clients/www/libaddr.snapwebsites.org/public_html/libaddr-$VERSION/.
#            #cp html/statistics.html /usr/clients/www/libaddr.snapwebsites.org/public_html/libaddr-$VERSION/.
#    fi
#fi

echo "Process started  on $start_date"
echo "Process finished on $end_date"

# vim: ts=4 sw=4 et
