Document: advgetopt
Title: Debian advgetopt Manual
Author: <insert document author here>
Abstract: This manual describes what advgetopt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/advgetopt/advgetopt.sgml.gz

Format: postscript
Files: /usr/share/doc/advgetopt/advgetopt.ps.gz

Format: text
Files: /usr/share/doc/advgetopt/advgetopt.text.gz

Format: HTML
Index: /usr/share/doc/advgetopt/html/index.html
Files: /usr/share/doc/advgetopt/html/*.html
