#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule


# delete the service files because otherwise snapinit will still
# attempt to start those services even though the binary is gone
#
rm -f /etc/snapwebsites/snapinit.d/service-images.xml
rm -f /etc/snapwebsites/snapinit.d/service-pagelist.xml
rm -f /etc/snapwebsites/snapinit.d/service-sendmail.xml
rm -f /etc/snapwebsites/snapinit.d/service-snapbackend.xml


#DEBHELPER#

# vim: ts=4 sw=4 et nocindent
