#!/bin/sh -e

#DEBHELPER#

# Source debconf library.
. /usr/share/debconf/confmodule

if [ "$1" = "configure" ]
then
    # Make sure that the core table exists
    #
    if ! snapcreatetables
    then
        echo "notice: snapcreatetables failed."
    fi

    for pkg in snapbackend snapsendmail snapimages snappagelist
    do
        if systemctl is-enabled ${pkg} 2> /dev/null
        then
            systemctl start ${pkg}
        fi
    done
fi

# vim: ts=4 sw=4 et nocindent
