#!/bin/sh
#
# Script used to build a source package specific to a sub-project.

DELETE_BUILD_FOLDER=true
if test $1 = "--keep-build-folder"
then
	DELETE_BUILD_FOLDER=false
	shift
fi
if test ! -d $1
then
	echo "error: $1 is not a sub-folder."
	exit 1;
fi;
# remove ending /
project=`echo "$1" | sed -e 'sX/$XX'`

cd $project

# Refresh all the output folders
rm -fr BUILD cmake 3rdParty
mkdir BUILD

# Make sure we have a build folder at the top
if test "$project" != "controlled_vars"
then
	mkdir -p BUILD/$project/doc
fi

ln -s ../cmake .
if test "$project" = "libQtCassandra"
then
	# We could use a softlink here, but then we'd get all 3rd party
	# library when at this point we just need thrift to compile
	# (the Cassandra include are in libQtCassandra/thrift-gencpp-cassandra)
	mkdir 3rdParty
	cp ../3rdParty/CMakeLists.txt 3rdParty/.
	cp ../3rdParty/thrift-0.8.0.tar.gz 3rdParty/.
fi;
cd BUILD
if ! cmake ..
then
	echo
	echo "error: cmake failed..."
	exit 1;
fi
if ! make
then
	echo
	echo "error: make failed..."
	exit 1;
fi
make package_source

# here we get a source package with a version
echo "---- main folder:"
ls
if test -d doc
then
	echo "---- doc folder:"
	ls doc
fi;

echo "----"
mv -vf $project-*.tar.gz ../../BUILD/$project/.

if test "$project" != "controlled_vars"
then
	if test -d doc
	then
		mv -vf doc/*$project-doc-*.tar.gz ../../BUILD/$project/doc/.
	else
		echo "*** WARNING *** -- no doc folder found, no documentation was extracted"
	fi
fi

cd ..
if $DELETE_BUILD_FOLDER
then
	rm -rf BUILD cmake 3rdParty
fi

echo "Done!"
