#!/bin/sh

# Full clean up
rm -rf BUILD

mkdir BUILD
cd BUILD

# You may change the compiler with something like this:
# (The CMAKE_C_COMPILER and CMAKE_CXX_COMPILER will NOT work)
#export CC=gcc-4.9
#export CXX=g++-4.9 cmake

# Configure and generate (Debug or Release)
cmake -DCMAKE_BUILD_TYPE=Debug ..

make
