#!/bin/sh

# Full clean up
rm -rf BUILD

mkdir BUILD
cd BUILD

# Configure and generate (Debug or Release)
cmake -DCMAKE_BUILD_TYPE=Debug ..

# You may change the compiler with something like this instead:
# CC=gcc-4.9 CXX=g++-4.9 cmake -DCMAKE_BUILD_TYPE=Debug ..
# The CMAKE_C_COMPILER and CMAKE_CXX_COMPILER will NOT work with thrift.

make
