#!/bin/sh
#
# Install various packages in order for the snap-server to compile
# at once--this is also available on our website; make sure to use sudo
# This is a helper script, you would be told about all of those libraries
# by the various projects cmake scripts.
#

# Qt changed from 4 to 5 when moving to 16.04
# libprocps3-dev changed to libprocps4-dev when moving to 16.04

apt-get install \
    closure-linter \
    cmake \
    doxygen \
    gcc \
    g++ \
    libboost-dev \
    libmagic-dev \
    libmagick++-dev \
    libprocps4-dev \
    libqt5script5 \
    libqt5scripttools5 \
    libqt5xmlpatterns5-dev \
    libqt5webkit5-dev \
    libssl-dev \
    libxml2-utils \
    qt5-default \
    qtscript5-dev \
    zip \
    zlib1g-dev

# TBD: get the cassandra-cpp-driver and cassandra-cpp-driver-dev packages

# Optional:

if test "$1" = "--optional"
then
    apt-get install \
       graphviz \
       libicu-dev \
       libqxcppunit-dev
else
    echo
    echo "WARNING:"
    echo "  Not installing optional packages by default. Re-run the script"
    echo "  the --optional command line option to force the installation"
    echo "  of the optional packages."
    echo
fi

# vim: ts=4 sw=4 et
