Document: libqtserialization
Title: Debian libqtserialization Manual
Author: <insert document author here>
Abstract: This manual describes what libqtserialization is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libqtserialization/libqtserialization.sgml.gz

Format: postscript
Files: /usr/share/doc/libqtserialization/libqtserialization.ps.gz

Format: text
Files: /usr/share/doc/libqtserialization/libqtserialization.text.gz

Format: HTML
Index: /usr/share/doc/libqtserialization/html/index.html
Files: /usr/share/doc/libqtserialization/html/*.html
