#!/bin/sh

### This script helps me run the tests in coverage mode which means that the
### library coverage can be generated.

set -e
start_date=`date`
mkdir -p tmp/coverage
rm -rf tmp/coverage/*
cd tmp/coverage
mkdir BUILD
cd BUILD
# request coverage in this build
export LIBTLD_COVERAGE=1
cmake ../../..
cd ..
echo
echo "***"
echo "*** compile"
echo "***"
VERBOSE=1 make -C BUILD
echo
echo "***"
echo "*** run"
echo "***"
BUILD/tests/tld_internal_test
BUILD/tests/tld_test
BUILD/tests/tld_test_emails
BUILD/tests/tld_test_full_uri
BUILD/tests/tld_test_object
cp ../../tests/effective_tld_names.dat .
BUILD/tests/tld_test_tld_names
if BUILD/src/tld_parser; then
	echo "tld_parser without a path did not generate an error";
	exit 1;
fi
if BUILD/src/tld_parser -h; then
	echo "tld_parser -h did not exit with an error";
	exit 1;
fi
if BUILD/src/tld_parser --help; then
	echo "tld_parser --help did not exit with an error";
	exit 1;
fi
echo
echo "***"
echo "*** gcov/lcov"
echo "***"

# Choose one of the following gcov commands
mkdir -p gcov
cd gcov
gcov -o ../BUILD/src/CMakeFiles/tld.dir/tld_emails.cpp.gcno ../../../src/tld_emails.cpp
cd ..


lcov --capture --directory ../.. --output-file coverage.info
mkdir -p html
genhtml --legend --demangle-cpp --no-branch-coverage --show-details coverage.info --output-directory html


echo "Process started  on $start_date"
echo "Process finished on `date`"
