#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule


# delete the service files because otherwise snapinit will still
# attempt to start those services even though the binary is gone
#
rm -f /etc/snapwebsites/services.d/service-snaplock.xml


if [ "$1" = "purge" ]
then
    # delete the snaplock logs
    rm -f /var/log/snapwebsites/snaplock.log*
    rm -f /var/log/snapwebsites/secure/snaplock.log*
fi

#DEBHELPER#

# vim: ts=4 sw=4 et nocindent
