#!/bin/bash
#
# File:
#      CMakeLists.txt
#
# Description:
#      Definitions to create the build environment with cmake
#
# Documentation:
#      See the CMake documentation.
#
# License:
#      csspp -- a CSS Preprocessor
#      Copyright (c) 2015 Made to Order Software Corp.
#
#      http://snapwebsites.org/
#      contact@m2osw.com
#
#      This program is free software; you can redistribute it and/or modify
#      it under the terms of the GNU General Public License as published by
#      the Free Software Foundation; either version 2 of the License, or
#      (at your option) any later version.
#
#      This program is distributed in the hope that it will be useful,
#      but WITHOUT ANY WARRANTY; without even the implied warranty of
#      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#      GNU General Public License for more details.
#
#      You should have received a copy of the GNU General Public License
#      along with this program; if not, write to the Free Software
#      Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#

set -e

cd ../source-repo
git pull origin master
rm -f snapcmakemodules_*.tar.gz controlledvars_*.tar.gz advgetopt_*.tar.gz csspp_*.tar.gz
dpkg-source -b snapCMakeModules
dpkg-source -b controlled_vars
dpkg-source -b advgetopt
dpkg-source -b csspp
cp snapcmakemodules_*.tar.gz controlledvars_*.tar.gz advgetopt_*.tar.gz csspp_*.tar.gz ../packages
cd ..
rm -rf tmp/csspp
mkdir -p tmp/csspp
cd tmp/csspp
tar xf ../../source-repo/snapcmakemodules_*.tar.gz
tar xf ../../source-repo/controlledvars_*.tar.gz
tar xf ../../source-repo/advgetopt_*.tar.gz
tar xf ../../source-repo/csspp_*.tar.gz
cp csspp/dev/MasterCMakeLists.txt CMakeLists.txt
VERSION=`dpkg-parsechangelog --show-field Version`
cd ..
tar czf csspp_${VERSION}.tar.gz csspp

# Local Variables:
# indent-tabs-mode: nil
# tab-width: 4
# End:

# vim: ts=4 sw=4 et
