Document: libqtcassandra
Title: Debian libqtcassandra Manual
Author: <insert document author here>
Abstract: This manual describes what libqtcassandra is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libqtcassandra/libqtcassandra.sgml.gz

Format: postscript
Files: /usr/share/doc/libqtcassandra/libqtcassandra.ps.gz

Format: text
Files: /usr/share/doc/libqtcassandra/libqtcassandra.text.gz

Format: HTML
Index: /usr/share/doc/libqtcassandra/html/index.html
Files: /usr/share/doc/libqtcassandra/html/*.html
