// Snap Manager CGI -- class to read a status file as generated by the daemon
// Copyright (C) 2016  Made to Order Software Corp.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#pragma once

#include <QString>

namespace snap_manager
{


class status_file
{
public:
                status_file(char const * filename);
                ~status_file();

    void        close();
    bool        open();
    bool        readline(QString & result);
    bool        readvar(QString & name, QString & value);
    bool        has_error() const;

private:
    std::string f_filename;
    int         f_fd = -1;
    FILE *      f_file = nullptr;
    bool        f_has_error = false;
};

} // namespace snap_manager
// vim: ts=4 sw=4 et
