#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

PACKAGENAME=snapwatchdog
if systemctl is-active ${PACKAGENAME}
then
    systemctl stop ${PACKAGENAME}
fi

if [ "$1" = "purge" ]
then
    # Remove data directory
    #
    rm -rf /var/lib/snapwebsites/${PACKAGENAME}

    # Remove all logs
    #
    rm -f /var/log/snapwebsites/${PACKAGENAME}.log*
    rm -f /var/log/snapwebsites/secure/${PACKAGENAME}.log*
fi

#DEBHELPER#

# vim: ts=4 sw=4 et nocindent
