debian/tmp/usr/bin/snapbackend                                usr/bin/
debian/tmp/usr/lib/snapwebsites/manager_plugins/libbackend.so usr/lib/snapwebsites/manager_plugins/
snapbackend/conf/snapbackend.timer                            \
snapbackend/conf/snapimages.service                           \
snapbackend/conf/snaplistjournal.service                      \
snapbackend/conf/snappagelist.service                         \
snapbackend/conf/snapsendmail.service                         lib/systemd/system/
