#!/bin/bash

set -e

if test $1 = "--full"
then
    FULL=true
    shift
else
    FULL=false
fi

start_date=`date`
SOURCE=`pwd`
MAJOR=`grep AS2JS_VERSION_MAJOR CMakeLists.txt | sed -e 's/^.*set(.*AS2JS_VERSION_MAJOR.*\([0-9]\+\).*$/\1/'`
MINOR=`grep AS2JS_VERSION_MINOR CMakeLists.txt | sed -e 's/^.*set(.*AS2JS_VERSION_MINOR.*\([0-9]\+\).*$/\1/'`
PATCH=`grep AS2JS_VERSION_PATCH CMakeLists.txt | sed -e 's/^.*set(.*AS2JS_VERSION_PATCH.*\([0-9]\+\).*$/\1/'`
VERSION="$MAJOR.$MINOR.$PATCH"
echo "***"
echo "*** as2js coverage for version $VERSION (`date`)"
echo "***"
mkdir -p tmp/coverage
rm -rf tmp/coverage/*
cd tmp/coverage
mkdir BUILD
cd BUILD
# request coverage in this build
dist=`cd ../../../../; pwd`/BUILD/dist
modules=$dist/share/cmake-2.8/Modules
cmake -DCMAKE_INSTALL_PREFIX:PATH=$dist \
    -DCMAKE_MODULE_PATH:PATH=$modules \
    -DCMAKE_BUILD_TYPE=Debug \
    -Das2js_compiler_COVERAGE:BOOL=ON \
    -DCMAKE_BUILD_TYPE:BOOL=Debug \
    -DCONTROLLEDVARS_INCLUDE_DIR=$dist/include \
    ../../..
cd ..
echo
echo "***"
echo "*** compile (`date`)"
echo "***"
VERBOSE=1 make -C BUILD
echo
echo "***"
echo "*** run (`date`)"
echo "***"
# TODO add a test of the version here against the version in include/as2js/as2js.h.in
if test `BUILD/tests/test_as2js --version` != "$VERSION"
then
    echo "the version of test_as2js (`BUILD/tests/test_as2js --version`) is not equal to the project version ($VERSION)"
    exit 1;
fi
if $FULL
then
    # We test the pipe status on exit to detect whether the test failed
    echo "Start running the tests on `date`" >test_log.txt
    echo >>test_log.txt
    BUILD/tests/test_as2js 2>&1 | tee -a test_log.txt; test ${PIPESTATUS[0]} -eq 0
    echo >>test_log.txt
    BUILD/tests/test_as2js --destructive As2JsStreamUnitTests::test_stdout_destructive 2>&1 | tee -a test_log.txt; test ${PIPESTATUS[0]} -eq 0
    echo >>test_log.txt
    BUILD/tests/test_as2js As2JsRCUnitTests::test_empty_home 2>&1 | tee -a test_log.txt; test ${PIPESTATUS[0]} -eq 0
    echo >>test_log.txt
    echo "Finished running the tests on `date`" >>test_log.txt
else
    # brief test while working on a specific test
    #BUILD/tests/test_as2js
    #BUILD/tests/test_as2js As2JsLexerUnitTests
    BUILD/tests/test_as2js As2JsNodeUnitTests
    #BUILD/tests/test_as2js As2JsOptimizerUnitTests
    # just in case, remove the log file if there is one
    rm -f test_log.txt
fi
echo
echo "***"
echo "*** gcov/lcov (`date`)"
echo "***"

# Choose one of the following gcov commands
mkdir -p gcov
cd gcov
gcov -o ../BUILD/src/CMakeFiles/as2js.dir/as2js.cpp.gcno ../../../src/as2js.cpp
cd ..


lcov --capture --directory BUILD --output-file coverage.info
# The following lcov options can be used under Ubuntu 14.10+
# Use --no-external and --base-directory $SOURCE
# to avoid /usr/include and other unwanted files
# (only available in lcov version 1.10+)
#lcov --capture --no-external --directory BUILD --base-directory $SOURCE --output-file coverage.info
mkdir -p html
genhtml --legend --demangle-cpp --no-branch-coverage --show-details coverage.info --output-directory html


end_date=`date`

if test -f test_log.txt
then
    echo "***"
    echo "*** publication to lcov.as2js.org (`date`)"
    echo "***"

    # Statistics
    echo "<html><head><title>as2js $VERSION statistics</title></head><body>" >html/statistics.html
    echo "<h3>Statistics of the as2js $VERSION code</h3><pre>" >>html/statistics.html
    cloc $SOURCE/include/ $SOURCE/lib/ $SOURCE/src/ >>html/statistics.html
    echo "</pre><h3>Statistics of the as2js $VERSION tests</h3><pre>" >>html/statistics.html
    cloc $SOURCE/tests/ >>html/statistics.html
    echo "</pre><h3>Statistics of as2js scripts $VERSION</h3><pre>" >>html/statistics.html
    cloc $SOURCE/scripts/ >>html/statistics.html
    echo "</pre></body></html>" >>html/statistics.html

    # Test output (Logs)
    echo "<html><head><title>as2js $VERSION test logs</title></head><body><h3>Logs for the as2js $VERSION tests</h3><p>Tests started on $start_date and finished on $end_date</p><pre>" >html/test_log.html
    cat test_log.txt >>html/test_log.html
    echo "</pre></body></html>" >>html/test_log.html

    # For publication, if that directory does not exist, you probably don't
    # have a website to display this data
    if test -d /usr/clients/www/lcov.as2js.org/public_html
    then
            cp $SOURCE/dev/index.php /usr/clients/www/lcov.as2js.org/public_html/.
            mkdir -p /usr/clients/www/lcov.as2js.org/public_html/as2js-$VERSION
            cp -r html/* /usr/clients/www/lcov.as2js.org/public_html/as2js-$VERSION/.
            #cp html/statistics.html /usr/clients/www/lcov.as2js.org/public_html/as2js-$VERSION/.
    fi
fi

echo "Process started  on $start_date"
echo "Process finished on $end_date"

# vim: ts=4 sw=4 et
