#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Remove files representing each service offered by this package
#
SERVICES_DIR=/usr/share/snapwebsites/services
rm -f $SERVICES_DIR/snapdbproxy.service

if [ "$1" = "purge" ]
then
    # delete the logs
    PACKAGENAME=snapdbproxy
    rm -f /var/log/snapwebsites/${PACKAGENAME}.log*
    rm -f /var/log/snapwebsites/secure/${PACKAGENAME}.log*
fi

#DEBHELPER#

# vim: ts=4 sw=4 et nocindent
