#!/bin/sh -e

#DEBHELPER#

# Source debconf library.
. /usr/share/debconf/confmodule


if [ "$1" = "configure" ]
then
    # Create the logfile because the snapwebsites user may have
    # difficulties with it otherwise during logrotate.
    #
    PKGNAME=snapdbproxy
    SNAPLOGDIR=/var/log/snapwebsites
    LOGFILE=${SNAPLOGDIR}/${PKGNAME}.log
    touch ${LOGFILE}
    chown snapwebsites:snapwebsites ${LOGFILE}
    chmod 640 ${LOGFILE}

    SNAPSECURELOGDIR=/var/log/snapwebsites/secure
    SECURELOGFILE=${SNAPSECURELOGDIR}/${PKGNAME}.log
    touch ${SECURELOGFILE}
    chown snapwebsites:snapwebsites ${SECURELOGFILE}
    chmod 640 ${SECURELOGFILE}

    # Create files representing each service offered by this package
    #
    SERVICES_DIR=/usr/share/snapwebsites/services
    touch $SERVICES_DIR/snapdbproxy.service

    if systemctl is-enabled ${PKGNAME} 2> /dev/null
    then
        systemctl start ${PKGNAME}
    fi

    # Make sure that the core tables exist
    # The core tables are defined in the library, but installed here
    # since it is only once we have snapdbproxy that we can install
    # said libraries...
    #
    #snapcreatetables -- at this time this could be too early (i.e.
    #                    the snapdbproxy takes some time to connnect
    #                    to the Cassandra database.)
    #
    #                    to palliate to this current limitation, we
    #                    instead run the command in snapserver and
    #                    snapbackend when those get installed
fi

# vim: ts=4 sw=4 et nocindent
