#!/bin/sh
set -e
if test "$1" = "-d"
then
	. dev/version
	rm -f ../BUILD/csspp/doc/csspp-doc-${VERSION}.tar.gz
	make -C ../BUILD/csspp/ csspp_Documentation
elif test "$1" = "-t"
then
	make -C ../BUILD/csspp/
	shift
	TEST="$1"
	if test -n "$TEST"
	then
		shift
		echo run with \"$TEST\"
	fi
	../BUILD/csspp/tests/csspp_tests --scripts scripts --version-script ../BUILD/csspp/scripts "$TEST" $*
elif test "$1" = "-i"
then
	make -C ../BUILD/csspp install
else
	make -C ../BUILD/csspp
fi
