#!/bin/sh
set -e
if test "$1" = "-d"
then
	. dev/version
	rm -f ../BUILD/csspp/doc/csspp-doc-${VERSION}.tar.gz
	make -C ../BUILD/csspp/ csspp_Documentation
elif test "$1" = "-t"
then
	make -C ../BUILD/csspp/
	shift
	TEST="$1"
	if test -n "$TEST"
	then
		shift
		echo run with \"$TEST\"
	fi
	../BUILD/csspp/tests/csspp_tests --scripts scripts --version-script ../BUILD/csspp/scripts "$TEST" $*
elif test "$1" = "-i"
then
	make -C ../BUILD/csspp install
elif test "$1" = "-c"
then
	if test -z "$2"
	then
		echo "the -c option requires a second option with the name of the test to run"
		exit 1
	fi
	make -C ../BUILD/csspp install
	../BUILD/csspp/tests/csspp_tests --scripts ../BUILD/dist/lib/csspp/scripts --show-errors "[$2]" 2>&1 | less
else
	make -C ../BUILD/csspp
fi
