#!/bin/bash
#
# Sample script to run make without having to retype the long path each time
# This will work if you built the environment using our ~/bin/build-snap script

if test -x ../cmake/scripts/mk
then
	../cmake/scripts/mk $*
else
	echo "error: could not locate the cmake mk script"
	exit 1
fi

