#!/bin/sh
if test "$1" = "-r"
then
	../BUILD/snapwebsites/src/snapinit --remove-lock
fi
../BUILD/snapwebsites/src/snapinit --debug --binary-path ../BUILD/snapwebsites/src:../BUILD/snapwatchdog/src start
