#!/bin/sh
if test "$1" = "-s"
then
	# only stop the snapserver
	# (very useful when you start the server the first time to
	# create the domains, websites, and initialize the first
	# website)
	../BUILD/snapwebsites/src/snapsignal --action snapserver STOP
else
	# stop all the snap services managed by snapinit on this computer
	../BUILD/snapwebsites/src/snapinit stop
fi
