#!/bin/sh -e

#DEBHELPER#

# Source debconf library.
. /usr/share/debconf/confmodule

if [ "$1" = "configure" ]
then
    PKGNAME=snapserver

    # Create files representing each service offered by this package
    #
    SERVICES_DIR=/usr/share/snapwebsites/services
    touch $SERVICES_DIR/snapserver.service

    # Make sure that the core table exists
    #
    if ! snapcreatetables
    then
        echo "notice: snapcreatetables failed."
    fi
fi

# vim: ts=4 sw=4 et nocindent
