#!/bin/sh -e

#DEBHELPER#

# Source debconf library.
. /usr/share/debconf/confmodule

if [ "$1" = "configure" ]
then
    PKGNAME=snapserver

    # Make sure that the core table exists
    #
    if ! snapcreatetables
    then
        echo "notice: snapcreatetables failed."
    fi

    if systemctl is-enabled ${PKGNAME} 2> /dev/null
    then
        systemctl start ${PKGNAME}
    fi
fi

# vim: ts=4 sw=4 et nocindent
