#!/bin/sh
if test "$1" = "-d"
then
	# Rebuild documentation on the spot
	rm -rf ../../BUILD/zipios2/doc/zipios-doc-2.0*
	make -C ../../BUILD/zipios2/ zipios_Documentation
	make -C ../../BUILD/zipios2/ install
else
	make -C ../../BUILD/zipios2/
fi
