debian/tmp/usr/bin/snappassword usr/bin/
debian/tmp/usr/lib/cgi-bin/snapmanager.cgi var/www/snapmanager/cgi-bin/
debian/tmp/usr/share/snapwebsites/bundles/bundle-*.xml usr/share/snapwebsites/bundles/
debian/tmp/usr/share/snapwebsites/html/snapmanager/* usr/share/snapwebsites/html/snapmanager/
debian/tmp/usr/share/snapwebsites/apache2/* usr/share/snapwebsites/apache2/
conf/snapmanagercgi-parser.xsl etc/snapwebsites/
conf/snapmanagercgi.properties usr/share/snapwebsites/logger/
conf/snapmanagercgi.properties etc/snapwebsites/logger/
conf/snapmanager-apache2.conf etc/apache2/sites-available/
conf/snapmanager-README.md etc/apache2/snap-conf/snapmanager/
conf/passwords-README.md etc/snapwebsites/passwords/
conf/index.html conf/favicon.ico var/www/snapmanager/public_html/
