#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule


if [ "$1" = "purge" ]
then
    # delete the snapmanagercgi logs if any
    #
    rm -f /var/log/snapwebsites/snapmanagercgi.log*
    rm -f /var/log/snapwebsites/secure/snapmanagercgi.log*

    # we create that file, so we want to remove it on a purge
    #
    rm -f /etc/snapwebsites/passwords/snapmanagercgi.pwd
fi

/usr/lib/snapwebsites/scripts/snapapacheinit remove


#DEBHELPER#

# vim: ts=4 sw=4 et nocindent
