#!/bin/sh
#
# Script used to quickly check out the firewall, without having to remember
# all the options. You must use sudo to run this script:
#
#    sudo showfw
#

IPTABLES=iptables
TYPE=filter
while test ! -z "$1"
do
	case "$1" in
	"-4")
		IPTABLES=iptables
		;;

	"-6")
		IPTABLES=ip6tables
		;;

	"--filter")
		TYPE=filter
		;;

	"--nat")
		TYPE=nat
		;;

	-h|"--help")
		echo "Usage: sudo `basename $0` [-4|-6] [--filter|--nat]"
		echo "  -4        to display the IPv4 tables, this is the default"
		echo "  -6        to display the IPv6 tables"
		echo "  --filter  to display the filter tables, this is the default"
		echo "  --nat     to display the nat tables"
		exit 0
		;;

	esac
	shift
done


$IPTABLES -t $TYPE -L -nvx | less -S
