#!/bin/sh

BUILD/snapwebsites/snapcommunicator/src/snapsignal snapcommunicator/STOP

#BUILD/snapwebsites/snapcommunicator/src/snapsignal snaplock/STOP
#BUILD/snapwebsites/snapcommunicator/src/snapsignal snapdnproxy/STOP
#BUILD/snapwebsites/snapcommunicator/src/snapsignal snapfirewall/STOP
#BUILD/snapwebsites/snapcommunicator/src/snapsignal snapserver/STOP
#BUILD/snapwebsites/snapcommunicator/src/snapsignal images/STOP
#BUILD/snapwebsites/snapcommunicator/src/snapsignal pagelist/STOP
#BUILD/snapwebsites/snapcommunicator/src/snapsignal sendmail/STOP
#BUILD/snapwebsites/snapcommunicator/src/snapsignal snapmanagerdaemon/STOP
#BUILD/snapwebsites/snapcommunicator/src/snapsignal snapwatchdog/STOP

