#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

if [ "$1" = "purge" ]
then
    # Since we place this file in the fail2ban folder, the folder
    # may not get removed properly
    #
    rm -f /var/lib/iplock/private/*
    rmdir --ignore-fail-on-non-empty /etc/fail2ban/action.d
    rmdir --ignore-fail-on-non-empty /etc/fail2ban /var/lib/iplock/private
fi

#DEBHELPER#

# vim: ts=4 sw=4 et nocindent
