#!/bin/sh
#
# File:
#      CMakeLists.txt
#
# Description:
#      Definitions to create the build environment with cmake
#
# Documentation:
#      See the CMake documentation.
#
# License:
#      csspp -- a CSS Preprocessor
#      Copyright (c) 2015-2017 Made to Order Software Corp.
#
#      http://snapwebsites.org/
#      contact@m2osw.com
#
#      This program is free software; you can redistribute it and/or modify
#      it under the terms of the GNU General Public License as published by
#      the Free Software Foundation; either version 2 of the License, or
#      (at your option) any later version.
#
#      This program is distributed in the hope that it will be useful,
#      but WITHOUT ANY WARRANTY; without even the implied warranty of
#      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#      GNU General Public License for more details.
#
#      You should have received a copy of the GNU General Public License
#      along with this program; if not, write to the Free Software
#      Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#

# Retrieve the project version from the main CMakeLists.txt file
MAJOR_VERSION=`grep 'set(CSSPP_VERSION_MAJOR ' CMakeLists.txt | sed -e 's/.*CSSPP_VERSION_MAJOR //' -e 's/).*//'`
MINOR_VERSION=`grep 'set(CSSPP_VERSION_MINOR ' CMakeLists.txt | sed -e 's/.*CSSPP_VERSION_MINOR //' -e 's/).*//'`
PATCH_VERSION=`grep 'set(CSSPP_VERSION_PATCH ' CMakeLists.txt | sed -e 's/.*CSSPP_VERSION_PATCH //' -e 's/).*//'`

# Define a couple more variables
VERSION=${MAJOR_VERSION}.${MINOR_VERSION}
FULL_VERSION=${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}

# Local Variables:
# indent-tabs-mode: nil
# tab-width: 4
# End:

# vim: ts=4 sw=4 et nocindent
